### ISSUE TITLE
linter to enforce consistent formatting across repo

### ISSUE THREAD

**Issue by lowellbander** [Community-Aid/ca-frontend#30]

**Comment by bluquar** [comment]
I added prettier in [588df010...](https://github.com/Community-Aid/ca-frontend/commit/588df010d39a32cc0dff14d42f7e764ce39674be), including configuring the prettier config in `package.json`. In my VSCode it automatically formats using prettier on save. I also added eslint in [acf9217d...](https://github.com/Community-Aid/ca-frontend/commit/acf9217dfc559c65e49d23ad95ce69eed6b5479f).

I think to tie this all together, we would need:
1. An eslint rule that checks whether prettier formatting is applied
2. A github integration that flags/blocks PRs with lint violations
