### ISSUE TITLE
Separate general purpose modules from Aid modules

### ISSUE THREAD

**Issue by bluquar** [Community-Aid/ca-frontend#49]
Eg AidTimeAgo should be GPTimeAgo (General Purpose) since there's nothing specific to this app unit. That will mean if we scrap this app and make a new one these GP modules will still be useful

**Comment by lowellbander** [comment]
this makes sense! I prefer word prefix tho, so that the PascalCase is
easier to scan

**Comment by bluquar** [comment]
That makes sense! Any ideas for a good word prefix? Preferably a short one

**Comment by bluquar** [comment]
Could be something unrelated like "Cat"

**Comment by bluquar** [comment]
We could also not use namespace prefixes and just separate by module directory. This seems to be a pattern in open source code I've seen so far

**Comment by lowellbander** [comment]
`Common` could also be a prefix, but perhaps less obvious that it's a Chris Barker Component
